### ISSUE TITLE
Error occur in about:debugging if privacy.firstparty.isolation enabled in about:config

### ISSUE THREAD

**Issue by z7z8th** [wooque/site-bleacher#1]
https://github.com/wooque/site-bleacher/blob/936493b5bfdbdf459ec9e398424f319ee78ba16a/common.js#L3

`Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. common.js:3
    getCookies moz-extension://537e171b-0c3b-4a4f-8418-f8543c037bcf/common.js:3`

`firstPartyDomain` should be set in `chrome.cookies.getAll({url: d.url, firstPartyDomain: domainOfTab}...)` if `browser.privacy.websites.firstPartyIsolate` is `true` in firefox.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites

**Comment by wooque** [comment]
Should be fixed in **1.0.17** (31fe019a56027b8c6268c4614f2117c926943b1c)
