### ISSUE TITLE
crashing Firefox v70

### ISSUE THREAD

**Issue by atomGit** [wooque/site-bleacher#11]
FF v70.0 on Linux
SB 1.1.0

not thoroughly tested; SB will crash the browser on different sites than those in the example, but i found this combo to be repeatable 99% or 100% of the time...

1. start FF
2. open: https://github.com/ghacksuserjs/ghacks-user.js/issues/776#issuecomment-546817097
3. middle click the link in the post to open AMO in a new tab and let it finish loading
4. middle click the AMO tab to close it - browser crashes

**Comment by atomGit** [comment]
there's more to it - uMatrix needs to be installed - i tested with uMatrix 1.4.0 (latest) and settings as follows...

* settings tab: all disabled
* my rules tab - everything removed and allowing all: `* * * allow`
* assets tab: all disabled
* more tab: all default

then follow the sequence in the last post

@gorhill

**Comment by atomGit** [comment]
looks like the same is true if uBlock O is installed (without uMatrix), though i didn't test with uBO default settings

**Comment by wooque** [comment]
Tried with fresh install of Firefox and SB and could not reproduce.
Could you try with new empty profile to see if it's profile specific.

**Comment by atomGit** [comment]
see 2nd post - you have to have uMatrix installed as well

**Comment by atomGit** [comment]
no, you're right, i couldn't reproduce on a clean profile - i thought i tested that - i'll have to do more testing

**Comment by atomGit** [comment]
i'm sure i tested on a clean profile before with only uM and SB but now i can't reproduce, even with my normal prefs.js uM and SB, so i don't know what's going on

ignore it for now and maybe i'll test more later

**Comment by nobura** [comment]
i have same issue

often crash on google mail or ads sitebypass like this http://iinspire.xyz/IcSku

**Comment by atomGit** [comment]
yeah, i see another user mentioned the same problem in a [review](https://addons.mozilla.org/en-US/firefox/addon/site-bleacher/reviews/?score=3)

it may not be limited to SB either - i installed [StoragErazor](https://addons.mozilla.org/en-US/firefox/addon/storagerazor/) yesterday and FF crashed immediately upon install

**Comment by nobura** [comment]
i think found the problem
firefox 70 
go to 

> about:config

Search for 
> dom.storage.next_gen

Set the preference to 

> False

**Comment by atomGit** [comment]
very nice work - a quick test here seems to confirm

found these while searching that pref...
[ToDo: diffs FF68-FF69 · Issue #766 · ghacksuserjs/ghacks-user.js](https://github.com/ghacksuserjs/ghacks-user.js/issues/766#issuecomment-526835183)
[Mozilla Provides Workaround for Firefox 70 Not Loading Sites](https://www.bleepingcomputer.com/news/software/mozilla-provides-workaround-for-firefox-70-not-loading-sites/)
[Firefox 70 not loading some pages or elements? Here is a fix - gHacks Tech News](https://www.ghacks.net/2019/10/29/firefox-70-not-loading-some-pages-or-elements-here-is-a-fix/)

**Comment by wooque** [comment]
It seems new LocalStorage implementation is buggy and on the road to be disabled in next point release.
Until it's disabled/fixed, workaround @wanglai8 suggested it's only solution.
