### ISSUE TITLE
Link to your ff addon page from git & also a test site for your addon

### ISSUE THREAD

**Issue by rugabunda** [wooque/site-bleacher#12]
Pls consider adding the following test link so people can easily verify for themselves the power of this amazing little addon... 

https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html

**Comment by rugabunda** [comment]
then check this guy out, you'll be glad you did https://www.youtube.com/channel/UCYVU6rModlGxvJbszCclGGw/videos

**Comment by wooque** [comment]
Thanks for suggestion, README updated, link added to addon page.

**Comment by rugabunda** [comment]
Old link is dead, here is the updated link to the latest sanitizing script:

https://arkenfox.github.io/TZP/ 
https://arkenfox.github.io/TZP/tests/sanitizing.html

**Comment by rugabunda** [comment]
Your addon is still #1...  i hope you keep it updated if there is anything better possible.

**Comment by wooque** [comment]
@rugabunda Unfortunately add-on is not maintained for years, I don't use it anymore.
