### ISSUE TITLE
Some sites bypassing clean of storage

### ISSUE THREAD

**Issue by 0oWow** [wooque/site-bleacher#16]
I'm using Firefox 76.0.1 64-bit in Kubuntu 20.04, but this also happens in Windows 10 in other versions, as this has happened for a short while.  

I notice when I visit certain sites, target.com for example, and then after closing the tab, I check "Manage Data" in Firefox Options and I will see storage still saved for target.com.  Target.com is definitely marked for clean.  Also I am running umatrix and ublock origin (all filters checked except languages).    

They are not the only websites, but they are my test example for the moment.  Is there anything I can do to see why they might be causing this?  Thanks for your work on this project!

**Comment by wooque** [comment]
That's because extension can't clean CacheStorage, that target.com uses, and probably some other sites.
There is no options for that in extension API for cleaning browser data. 
Chrom(ium) has that option, but unfortunately Firefox extension API lags in features compared to Chrome's one.

**Comment by geeknik** [comment]
Firefox 77 will support clearing IndexDB by hostname if that helps: https://bugzilla.mozilla.org/show_bug.cgi?id=1551301. 

Firefox 77 will also support clearing ServiceWorkers by hostname:  https://bugzilla.mozilla.org/show_bug.cgi?id=1632990.

After that, Firefox 78 will support clearing cache and pluginData by hostname: https://bugzilla.mozilla.org/show_bug.cgi?id=1636784. 

These options are available for testing in Firefox Nightly.

**Comment by wooque** [comment]
@geeknik thanks for the heads up!

**Comment by geeknik** [comment]
Sure, no problem, Nightly is my daily browser so if you need help testing anything let me know. \m/

**Comment by 0oWow** [comment]
> 
> 
> That's because extension can't clean CacheStorage, that target.com uses, and probably some other sites.
> There is no options for that in extension API for cleaning browser data.
> Chrom(ium) has that option, but unfortunately Firefox extension API lags in features compared to Chrome's one.

Thanks.  Glad to hear that Firefox 78 will support it.  :)
