### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mioni** [wooque/site-bleacher#17]
When I access this site it appears another site that I access too, why does it appear? It happens with other sites that I access too
![](https://i.snipboard.io/3eBGZv.jpg)

**Comment by wooque** [comment]
It's because site loads third-party scripts that set third-party cookies. 
I personally always disable third-party(cross-site) cookies, it rarely breaks some site and it's great measure against tracking.

**Comment by Mioni** [comment]
So do you recommend I disable the blocking third-party cookies?
![Annotation 2020-06-14 140608](https://user-images.githubusercontent.com/6830783/84599413-3ea37700-ae48-11ea-8f94-f91cd8cf32bb.png)

**Comment by wooque** [comment]
@Mioni no, I recommend blocking third-party cookies

**Comment by Mioni** [comment]
Ok, thank you!
