### ISSUE TITLE
change-log?

### ISSUE THREAD

**Issue by atomGit** [wooque/site-bleacher#4]
i didn't see a change log published anywhere - is there one? and if not, could you please consider making one?

thanks

**Comment by wooque** [comment]
There is one, commit log is a change log :) 
I'll create one for future changes.

**Comment by atomGit** [comment]
yes, i read the commit log and in this case it's short and informative, but when there's many complex commits a commit log can be difficult to understand

on another note, i'm curious about entropy - as i understand it (i don't know JS) it appears you are injecting some sort of identifier into the IDB storage so that you know which part of the storage to delete later (when a domain is re-visited)

my question is, can that identifier be read by the domain that set the storage? does it raise entropy/make fingerprinting easier?

this is perhaps something you may want to detail in your readme and AMO descrip

**Comment by wooque** [comment]
I'm not injecting any identifier into IndexedDB, so entropy is neither raised nor decreased. 
Extension is injecting little script in every page that's intercepts open calls and records database names, that are saved in extension storage only accessible to extension. 
That's how extension knows what IndexedDBs are used on page and what's needed to be deleted.

**Comment by atomGit** [comment]
so does JS need to be enabled in order for SB to work?

i use uMatrix and disable JS globally, then allow on a per-domain basis

**Comment by wooque** [comment]
Yes, thou it would should work with cookies without javascript

**Comment by atomGit** [comment]
ouch - i would think that your audience is going to be people that are concerned with privacy/security and those people are highly unlikely to enable cookies or JS globally - they are likely to be running uBlock O, uMatrix, NoScript, etc. and blocking JS globally

**Comment by wooque** [comment]
I meant it will clean cookies without JS, but for cleaning LocalStorages and IndexedDBs it will need JS, I don't know if it is posible to do this without JS, thou without JS site can't use LocalStorage or IndexedDBs anyway.

**Comment by atomGit** [comment]
> thou without JS site can't use LocalStorage or IndexedDBs anyway.

yes, i forgot about that - thanks
