### ISSUE TITLE
clean Service Workers?

### ISSUE THREAD

**Issue by atomGit** [wooque/site-bleacher#5]
does SB clean Service Worker cache? and if not, would that be possible to add?

**Comment by wooque** [comment]
It doesn't, but I'll look if it could be possible

**Comment by atomGit** [comment]
if you haven't already looked, perhaps this might be a starting point...

[ServiceWorkerRegistration.unregister() - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister)

[WindowOrWorkerGlobalScope.setTimeout() - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout)

[Functions and classes available to Web Workers - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers)

**Comment by wooque** [comment]
Version 1.1.0 cleans service workers and more

**Comment by atomGit** [comment]
wow, thank you so much - fantastic!

> Remove automatically cookies, local storages, IndexedDBs, service workers, cache storages, filesystems and webSQLs

can you explain what all is covered by cache storages, filesystems and webSQLs?

**Comment by wooque** [comment]
Don't really know :)
It's from Chrome extension docs: https://developer.chrome.com/extensions/browsingData

**Comment by atomGit** [comment]
when i updated SB i got the new permissions prompt to access browsing history - it looks like browsing history is not cleared, which is good

Q: do all of SB's functions, including the new ones, work with FF?

**Comment by wooque** [comment]
It should, except Firefox does not support cleaning cacheStorage, fileSystems, webSQL, thou they don't support WebSQL at all.

**Comment by wooque** [comment]
Updated addon description on addons.mozilla.org to reflect that
