### ISSUE TITLE
Service workers removed for whitelisted sites

### ISSUE THREAD

**Issue by r13s** [wooque/site-bleacher#7]
* **Firefox 68.0.1 x64**
* **Site Bleacher 1.1.0**

**Actual behavior:**

1. Add a site using a service worker, for example, YouTube, to whitelist.
2. Open `about:serviceworkers` and make sure that the YouTube service worker is registered.
3. Open any non-whitelist site in new tab.
4. Close tab from step 3.
5. Open `about:serviceworkers` and make sure that no service worker is registered.

**Expected behavior:**
* Service workers for whitelisted sites should not be removed.

Thank You.

**Comment by wooque** [comment]
This is problem with Firefox `browsingData.remove` extension API implementation (Chrome doesn't have this problem) which doesn't support removing service workers for specific domains, so when remove is called all service workers are removed.
If you or someone else has a workaround I happily to implement it.

**Comment by r13s** [comment]
How about unregistering non-whitelisted service workers instead of deleting them? Maybe something like the automated functionality of [this extension](https://github.com/jingyu9575/service-worker-control)?

Will it be difficult to implement or will it work slowly?

I'm not a programmer, sorry.

**Comment by r13s** [comment]
No, it was a bad idea, so I close it. Thanks.
