### ISSUE TITLE
Doesnt work for 1st party persistent cookie in git container

### ISSUE THREAD

**Issue by rugabunda** [wooque/site-bleacher#8]
Tested on the following page, only removed first party cookie on github.io after deleting git container, rebooting browser. 

https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html

**Comment by wooque** [comment]
I reproduced the issue, but I don't have currently time (in the next 2 weeks) to investigate and fix the issue. Will fix it as soon as I find some time for it.

**Comment by rugabunda** [comment]
Awesome, looking forward to future updates!

**Comment by wooque** [comment]
Fixed in 1.2.0

**Comment by rugabunda** [comment]
OMFG YOU DID SUCH A GOOD MF JOB MOAB THIS ADDON IS ! YEAAH. Eat your heart out bill
